import Head from 'next/head'

import Navbar from '../layout/navbar';
import Footer from '../layout/footer';

import { Typography } from '@material-ui/core';
import styles from '../styles/About.module.css'

export default function Home() {
  return (
    <div id={styles.body}>
      <Head>
        <title>Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="utf-8"/>
        <meta name="author" content="DiosPlon" />
        <meta name="robots" content="index"/>
        <meta httpEquiv="expires" content="23200"/>
        <meta name="copyright" content="CannibalCommunity es dueña de esta patente y todo este diseño" />
        <meta name="description" content="Describimos las filosofias de nuestra empresa, junto con nuestro objetivo y nuestro modelo de negocio"/>
        <meta name="keywords" content="servicios, presentacion serviout, constructores eficientes, contratistas bogota, contratistas cundinamarca" />
      </Head>
      <Navbar/>

      <main className={styles.container}>
        <div className={styles.concepto}>
          <h5 className={styles.title}>
            Filosofía 
          </h5>

          <p className={styles.parrafo}>
          Sabemos las necesidades y requerimientos que tienen nuestros clientes, por esta razón nos enfocamos en tres pilares. <span className={styles.clave}>Calidad</span>, <span className={styles.clave}>Garantia</span> y <span className={styles.clave}>Compromiso</span>, Llegando así a el cumplimiento  total en cada uno de los servicios realizados.
          </p>
        
        </div>

        <div className={styles.info}>
          <div className={styles.data}>
            <h6 className={styles.title}>Misión.</h6>
            <p className={styles.parrafo}>
              Somos una empresa dedicada a la prestación de servicios de (Construcción, Telecomunicaciones y Mudanzas) para hogares y empresas con un personal altamente calificado, teniendo como objetivo innovar estos tres sectores. 
            </p>
          </div>
          <div className={styles.data}>
            <h6 className={styles.title}>Visión.</h6>
            <p className={styles.parrafo}>
            Sabemos el compromiso que tenemos con nuestros clientes , por este motivo para el año 2025 contaremos con todas las normas iso , las cuales nos certificaran en la calidad  en la elaboración de nuestros procesos, además de Implementar una app la cual ayude a los usuarios a buscar nuestros servicios de una forma más práctica y eficaz.
            </p>
          </div>
        </div>

        

      </main>
      <Footer />
      
    </div>
  )
}
